run:
  tests: true
  build-tags: [ ]

issues:
  max-same-issues: 0

linters-settings:
  exhaustive:
    default-signifies-exhaustive: true

  depguard:
    rules:
      main:
        list-mode: strict
        allow:
          - $gostd
          - github.com/assurrussa/gobus

  forbidigo:
    forbid:
      - '^(fmt\.Print(|f|ln)|print|println)$'
      - 'errors\.Wrap'
      - 'errors\.Cause'

  gci:
    sections:
      - standard
      - default
      - prefix(github.com/assurrussa/gobus)

  godox:
    keywords:
      - FIXME
      - TODO

  govet:
    enable-all: true
    disable:
      - fieldalignment
      - shadow

  lll:
    line-length: 130
    tab-width: 1

  ginkgolinter:
    suppress-len-assertion: false
    suppress-nil-assertion: false
    suppress-err-assertion: false
    suppress-compare-assertion: false
    suppress-async-assertion: false
    allow-havelen-zero: false

  nolintlint:
    allow-no-explanation: [ "lll" ]
    require-explanation: true

  revive:
    severity: error
    rules:
      - name: argument-limit
      - name: atomic
      - name: bare-return
      - name: blank-imports
      - name: bool-literal-in-expr
      - name: comment-spacings
      - name: confusing-results
      - name: context-as-argument
        arguments:
          - allowTypesBefore: "*testing.T" # https://go-review.googlesource.com/c/lint/+/145237
      - name: context-keys-type
      - name: datarace
      - name: deep-exit
      - name: defer
      - name: dot-imports
      - name: duplicated-imports
      - name: early-return
      - name: empty-lines
      - name: empty-block
      - name: error-naming
      - name: error-return
      - name: error-strings
      - name: errorf
      - name: exported
      - name: identical-branches
      - name: if-return
      - name: increment-decrement
      - name: indent-error-flow
      - name: package-comments
      - name: range
      - name: range-val-address
      - name: range-val-in-closure
      - name: receiver-naming
      - name: redefines-builtin-id
      - name: string-of-int
      - name: superfluous-else
      - name: time-equal
      - name: time-naming
      - name: unexported-return
      - name: unhandled-error
        arguments: [ "fmt.Fprint", "fmt.Print", "fmt.Printf", "fmt.Println" ]
      - name: unreachable-code
      - name: use-any
      - name: unused-parameter
      - name: var-declaration
      - name: var-naming
      - name: waitgroup-by-value

linters:
  disable-all: true
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - contextcheck
    - depguard
    - durationcheck
    - errcheck
    - errchkjson
    - errname
    - execinquery
    - exhaustive
    - exportloopref
    - forbidigo
    - gci
    - ginkgolinter
    - goconst
    - gocritic
    - gocyclo
    - godot
    - godox
    - gofmt
    - gofumpt
    - goheader
    - goimports
    - gomoddirectives
    - gomodguard
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - importas
    - ineffassign
    - lll
    - loggercheck
    - makezero
    - misspell
    - musttag
    - nakedret
    - nestif
    - nilerr
    - nilnil
    - noctx
    - nolintlint
    - nosprintfhostport
    - prealloc
    - predeclared
    - promlinter
    - reassign
    - revive
    - rowserrcheck
    - staticcheck
    - stylecheck
    - sqlclosecheck
    - tagliatelle
    - tenv
    - testableexamples
    - testpackage
    - thelper
    - tparallel
    - typecheck
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - wastedassign
    - whitespace